portal/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.contrib import admin


admin.autodiscover()

from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import search_view_factory
from portal.core.views import SearchViewSites
from rss_feed import UltimasNoticias

sqs = SearchQuerySet().order_by('-data_publicacao')

urlpatterns = patterns('',
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/static/facicon.ico', permanent=True)),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
                       url(r'^conteudo/', include('portal.conteudo.urls', namespace='conteudo')),
                       url(r'^selecao/', 'portal.core.views.selecao', name='selecao'),
                       url(r'^dirf/', 'portal.dirf.views.download', name='download'),
                       url(r'^admin_site_menu/(?P<site_id>\d+)/$', 'portal.core.views.admin_site_menu',
                           name='admin_site_menu'),


                       url(r'buscar/$', search_view_factory(
                           view_class=SearchViewSites,
                           template='search/search.html',
                           searchqueryset=sqs,
                           form_class=ModelSearchForm
                       ), name='buscar'),

                       # url(r'^guiadecursos/', 'portal.cursos.views.listagrupodecursos', name='listagrupodecursos'),
                       url(r'^cursos/(?P<slug>[\w_-]+)/(?P<campus>\d+)/(?P<formacao>\d+)/$', 'portal.cursos.views.listacursosdogrupo',
                           name='listacursosdogrupo'),
                       url(r'^curso/(?P<slug>[\w_-]+)/$', 'portal.cursos.views.exibecurso', name='exibecurso'),
                       url(r'^guiadecursoportal/', 'portal.cursos.views.guiadecursoportal', name='guiadecursoportal'),
                       url(r'^jsonformacao/(?P<formacao_id>\d+)/$', 'portal.cursos.views.jsonformacao',
                           name='jsonformacao'),
                       url(r'^jsoncampi/(?P<campus_id>\d+)/$', 'portal.cursos.views.jsoncampi', name='jsoncampi'),
                       url(r'^jsoncursos/(?P<curso_id>\d+)/$', 'portal.cursos.views.jsoncursos', name='jsoncursos'),
                       url(r'^json_campi/(?P<formacao_id>\d+)/$', 'portal.core.views.json_campi', name='json_campi'),
                       url(r'^json_cursos/(?P<formacao_id>\d+)/(?P<campus_id>\d+)/$', 'portal.core.views.json_cursos',
                           name='json_cursos'),

                       # urls para agenda de compromissos do reitor
                       url(r'^agenda/$', 'portal.agenda.views.compromissos', name='agenda'),
                       url(r'^agenda/(?P<dia>\d{2})/(?P<mes>\d{2})/(?P<ano>\d{4})/$', 'portal.agenda.views.compromissos', name='agenda'),

                       # urls de redirecionamento do antigoportal
                       url(r'^noticias/', 'portal.core.views.redirecionar_antigoportal', name='antigo_noticias'),
                       # url(r'^noticias/(?P<id_noticia>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^licitacoes/', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/(?P<id_licitacao>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^post/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file_from_name/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^pesquisar/', 'portal.core.views.redirecionar_antigoportal'),
                       # fim do redirecionamento de urls do antigoportal


                       url(r'^inicio/$', 'portal.core.views.home', name='home'),
                       url(r'^$', 'portal.core.views.hotsite', name='hotsite'),

                       # url para arquivo html de autenticidade para o google search console
                       url(r'^googlef0c85b6fba6510c7.html$', TemplateView.as_view(template_name="googlef0c85b6fba6510c7.html")),

                       # url para arquivo robots.txt
                       url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt")),

                       # url para arquivo wpad.dat
                       url(r'^wpad.dat$', TemplateView.as_view(template_name="wpad.dat")),

                       # url para favicon.ico
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/staticfiles/favicon.ico', permanent=True)),

                       # rss
                       # (r'^rss/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': {'ultimas': UltimasNoticias}}),
                       (r'^rss/$', UltimasNoticias()),
                       )

# Trecho utilizado para que o django sirva os arquivos do diretorio media
from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

portal/cursos/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils.translation import ugettext_lazy as _
from filer.fields.file import FilerFileField


# class Campus(models.Model):
#     nome = models.CharField(max_length=50, verbose_name=u'Nome do Campus')
#
#     class Meta:
#         verbose_name = u'Campus'
#         verbose_name_plural = u'Campi'
#
#     def __unicode__(self):
#         return self.nome


class Formacao(models.Model):
    nome = models.CharField(max_length=100, verbose_name=u'Nome da Formação')

    class Meta:
        verbose_name = _(u'Tipo de Formacao')
        verbose_name_plural = _(u'Tipos de Formacoes')

    def __unicode__(self):
        return self.nome

    # Doutorado
    # Mestrado
    # Especialização
    # Curso Superior
    # Curso Técnico Integrado ao Ensino Médio
    # Curso Técnico Subsequente
    # Curso Técnico Integrado ao Ensino Médio na modalidade Proeja


class GrupoCursos(models.Model):
    nome = models.CharField(max_length=80, verbose_name=u'Nome Genérico para Curso', unique=True,
                            help_text=u'Ex.: Licenciatura em Matemática')
    slug = models.SlugField(max_length=250, verbose_name=u'Identificador', unique=True,
                            help_text=u'Texto que identificará a URL deste item (não deve conter espaços ou '
                                      u'caracteres especiais)')

    class Meta:
        verbose_name = _(u'Grupo de Cursos')
        verbose_name_plural = _(u'Grupo de Cursos')

    def __unicode__(self):
        return self.nome


class Curso(models.Model):
    TURNO = (
        ('MAT', u'Matutino'),
        ('VES', u'Vespertino'),
        ('NOT', u'Noturno'),
        ('INT', u'Integral'),
    )
    nome = models.CharField(max_length=100, verbose_name=u'Nome do Curso',
                            help_text=u'Ex.: Licenciatura em Matemática Noturno')
    slug = models.SlugField(max_length=250, verbose_name=u'Identificador', unique=True,
                            help_text=u'Texto que identificará a URL deste item (não deve conter espaços ou '
                                      u'caracteres especiais)')
    formacao = models.ForeignKey('Formacao', verbose_name=u'Tipo de Formação')
    campus = models.ForeignKey('core.Campus', verbose_name=u'Câmpus')
    turno = models.CharField(max_length=3, choices=TURNO, verbose_name=u'Turno do Curso')
    descricao = models.TextField(verbose_name=u'Descrição')
    email = models.EmailField(verbose_name=u'email', null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    grupo = models.ForeignKey('GrupoCursos')

    class Meta:
        verbose_name = u'Curso'
        verbose_name_plural = u'Cursos'

    def __unicode__(self):
        return u'%s - %s' % (self.nome, self.campus)

    @models.permalink
    def get_absolute_url(self):
        return 'exibecurso', (), {'slug': self.slug}


class AnexoCurso(models.Model):
    descricao = models.CharField(max_length=250, verbose_name=u'Descrição do anexo')
    arquivo = FilerFileField(related_name='anexos_curso')
    curso = models.ForeignKey('Curso', verbose_name=u'Curso')

    class Meta:
        verbose_name = _(u'Anexo')
        verbose_name_plural = _(u'Anexos')

    def __unicode__(self):
        return self.descricao

    # |---------|
    # |Formacao |
    # |---------|
    #     |1
    #     |
    #     |n
    # |------| n     1|-------------|n
    # |Curso |--------| GrupoCursos |
    # |------|        |-------------|
    #     |n
    #     |
    #     |1
    # |------------|
    # |core.Campus |
    # |------------|

portal/cursos/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms import ModelForm
from portal.cursos.models import Curso
from portal.core.forms import TinyMCEEditor


class CursoForm(ModelForm):
    class Meta:
        model = Curso

        fields = ('nome', 'slug', 'formacao', 'campus', 'turno', 'descricao', 'email', 'url', 'grupo')

        widgets = {
            'descricao': TinyMCEEditor(),
        }

portal/cursos/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from django.views.decorators.cache import never_cache
from portal.cursos.models import Curso, GrupoCursos
from django.http import HttpResponse  # httresponse para usar com json
import json  # json para usar no select com ajax
from django.core.urlresolvers import reverse

from portal.core.decorators import contar_acesso


def listadedicionarios(queryset):
    lista = []
    for l in queryset:
        d = dict()
        d["formacao_id"] = l[0]
        d["formacao_nome"] = l[1]
        d["campus_id"] = l[2]
        d["campus_nome"] = l[3]
        d["grupo_id"] = l[4]
        d["grupo_nome"] = l[5]
        d["grupo_slug"] = l[6]
        d["grupo_url"] = reverse('listacursosdogrupo', kwargs={'slug': l[6], 'campus': l[2], 'formacao': l[0]})
        lista.append(d)
    return lista


def jsonformacao(request, formacao_id):
    queryset = Curso.objects.select_related().filter(formacao=formacao_id).values_list(
        'formacao__id', 'formacao__nome', 'campus__id', 'campus__nome', 'grupo__id', 'grupo__nome', 'grupo__slug'
    ).order_by('formacao__nome').distinct()
    dados = listadedicionarios(queryset)
    return HttpResponse(json.dumps(dados), {'mimetype': "application/json"})


def jsoncampi(request, campus_id):
    queryset = Curso.objects.select_related().filter(campus=campus_id).values_list(
        'formacao__id', 'formacao__nome', 'campus__id', 'campus__nome', 'grupo__id', 'grupo__nome', 'grupo__slug'
    ).distinct()
    dados = listadedicionarios(queryset)
    return HttpResponse(json.dumps(dados), {'mimetype': "application/json"})


def jsoncursos(request, curso_id):
    queryset = Curso.objects.select_related().filter(grupo=curso_id).values_list(
        'formacao__id', 'formacao__nome', 'campus__id', 'campus__nome', 'grupo__id', 'grupo__nome', 'grupo__slug'
    ).distinct()
    dados = listadedicionarios(queryset)
    return HttpResponse(json.dumps(dados), {'mimetype': "application/json"})


def listagrupodecursos(request, queryset):
    formacao = Curso.objects.select_related('Formacao').values('formacao__id', 'formacao__nome').order_by('formacao__nome').distinct()
    #campi = Curso.objects.select_related('Campus').values('campus__id', 'formacao__id', 'campus__nome').distinct()
    campi = Curso.objects.select_related('Campus').values('campus__id', 'campus__nome').distinct()
    grupo_cursos = Curso.objects.select_related('GrupoCursos').values('grupo__id', 'grupo__nome',
                                                                      'grupo__slug').distinct()

    return render(
        request, 'cursos/listagrupodecursos.html',
        {
            'formacao': formacao,
            'grupo_cursos': grupo_cursos,
            'campi': campi,
            'queryset': queryset,
        }
    )


def listacursosdogrupo(request, slug, campus, formacao):
    grupo = get_object_or_404(GrupoCursos, slug=slug)
    # cursos = Curso.objects.select_related('Campus').filter(grupo__slug=slug)
    cursos = Curso.objects.filter(grupo=grupo, campus=campus, formacao=formacao)
    return render(request, 'cursos/listacursos.html', {'grupo': grupo, 'cursos': cursos, })


@never_cache
@contar_acesso
def exibecurso(request, slug):
    curso = get_object_or_404(Curso, slug=slug)
    return render(request, 'cursos/exibecurso.html', {'curso': curso})


def guiadecursoportal(request):
    if request.method == 'POST':
        if int(request.POST.get('cursos')) > 0:
            return listacursosdogrupo(request, GrupoCursos.objects.get(id=request.POST.get('cursos')).slug, request.POST.get('campi'), request.POST.get('formacao'))
        elif int(request.POST.get('campi')) > 0:
            queryset = Curso.objects.select_related().values(
                'formacao__id', 'formacao__nome', 'campus__id', 'campus__nome', 'grupo__id', 'grupo__nome',
                'grupo__slug').filter(campus=request.POST.get('campi')).order_by('formacao__nome').distinct()
            return listagrupodecursos(request, queryset)
        elif int(request.POST.get('formacao')) > 0:
            queryset = Curso.objects.select_related().values(
                'formacao__id', 'formacao__nome', 'campus__id', 'campus__nome', 'grupo__id', 'grupo__nome',
                'grupo__slug').filter(formacao=request.POST.get('formacao')).distinct()
            return listagrupodecursos(request, queryset)

        else:
            return listagrupodecursos(request, '')
    elif request.method == 'GET':
        return listagrupodecursos(request, '')
    else:
        return listagrupodecursos(request, '')

portal/cursos/templates/cursos/exibecurso.html
{% extends 'core/detalhe.html' %}

{% block breadcrumbs %}
    <li><a href="{% url 'guiadecursoportal' %}">Guia de Cursos</a></li>
    <li><a href="{% url 'listacursosdogrupo' curso.grupo.slug curso.campus_id curso.formacao_id %}">Cursos</a></li>
    <li class="current">{{ curso.nome|truncatewords:"5" }}</li>
{% endblock %}

{% block edicao %}
    {% if user.is_authenticated %}
        {% if perms.cursos.change_curso %}
            <div class="row padding-top">
                <div class="medium-12 columns text-right">
                    <a href="{% url 'admin:cursos_curso_change' curso.id %}">
                        <i class="fi-page-edit"></i> Editar curso
                    </a>
                    {% load contador_tags %}
                    / Visualizações: {% contador %}
                </div>
            </div>
        {% endif %}
    {% endif %}
{% endblock edicao %}

{% block conteudo %}
    <div class="row padding-bottom">
        <div class="row">
            <h1 class="justificado" id="titulo">Curso: {{ curso.nome }}</h1>
        </div>
        <div class="row">
            <p><strong>Formação:</strong> {{ curso.formacao }}</p>

            <p><strong>Campus:</strong> {{ curso.campus }}</p>

            <p><strong>Turno:</strong> {{ curso.get_turno_display }}</p>

            {% autoescape off %}
                <article>
                    <p><strong>Descrição:</strong> {{ curso.descricao|safe }}</p>
                </article>
            {% endautoescape %}
            {% if curso.email.strip|length > 0 %}
                <p><strong>Contato:</strong> {{ curso.email }}</p>
            {% endif %}
            {% if curso.url.strip|length > 0 %}
                <p><strong>Site do curso:</strong> <a href="{{ curso.url }}">{{ curso.url }}</a></p>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="medium-12 columns">
            {% if curso.anexocurso_set.all %}
                <h2 class="fundo-vermelho no-padding text-center">Anexos</h2>
                {% for arq in curso.anexocurso_set.all %}
                    <div class="row padding-bottom">
                        <a href="{{ arq.arquivo.url }}" target="_blank"><i
                                class="fi-download texto-tamanho-medio alinhamento-vertical">
                        </i>{{ arq.descricao }}
                        </a>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock conteudo %}

portal/cursos/templates/cursos/listacursos.html
{% extends 'core/lista.html' %}
{% block breadcrumbs %}
    <li><a href="{% url 'guiadecursoportal' %}">Guia de Cursos</a></li>
    <li class="current"><a href="#">Cursos</a></li>
{% endblock %}
{% block listagem %}
    <div class="row padding-top-bottom">
        <div class="small-12 columns">

            <div class="row padding-top-bottom">
                <h1>{{ grupo.nome }}</h1>
            </div>
            <div class="row padding-top-bottom">
                <h2>Cursos ofertados:</h2>
                {% for c in cursos %}
                    <div class="row padding-bottom-duplo">
                        <div class="row hover-cinza-claro">
                            <a href="{% url 'exibecurso' c.slug %}">
                                <div class="row">
                                    <div class="small-12 columns borda-esquerda">
                                        <p class="no-margin espacamento-medio">{{ c.nome }} - {{ c.campus }} -
                                            Formação: {{ c.formacao }} - Turno: {{ c.get_turno_display }}</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

portal/cursos/templates/cursos/listagrupodecursos.html
{% extends 'core/lista.html' %}
{% block breadcrumbs %}
    <li class="current"><a href="{% url 'guiadecursoportal' %}">Guia de Cursos</a></li>
{% endblock %}
{% block listagem %}
    <div class="row padding-top-bottom">
        <div class="small-12 columns">
            <form id="formuladio" name="formulario" method="post">{% csrf_token %}
                <div class="row fundo-cinza padding-all">
                    <div class="small-4 large-4 columns">
                        <label>Filtrar pela formação
                            <select id="filtroformacao" name="filtroformacao">
                                <option value="0">--------</option>
                                {% for f in formacao %}
                                    <option value="{{ f.formacao__id }}">{{ f.formacao__nome }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    <div class="small-4 large-4 columns">
                        <label>Filtrar pelo Câmpus
                            <select id="filtrocampi" name="filtrocampi">
                                <option value="0">--------</option>
                                {% for c in campi %}
                                    <option value="{{ c.campus__id }}">{{ c.campus__nome }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                    <div class="small-4 large-4 columns">
                        <label>Filtrar pelo curso
                            <select id="filtrocursos" name="filtrocursos">
                                <option value="0">--------</option>
                                {% for g in grupo_cursos %}
                                    <option value="{{ g.grupo__id }}">{{ g.grupo__nome }}</option>
                                {% endfor %}
                            </select>
                        </label>
                    </div>
                </div>
            </form>
        </div>
        <div id="resultado" class="small-12 columns hover-cinza-medio">
            {% if queryset %}
                {% for q in queryset %}
                    <div class="row padding-all">
                        <div class="small-4 large-4 columns">{{ q.formacao__nome }}</div>
                        <div class="small-4 large-4 columns">{{ q.campus__nome }}</div>
                        <div class="small-4 large-4 columns"><a href="{% url 'listacursosdogrupo' q.grupo__slug q.campus__id q.formacao__id %}">{{ q.grupo__nome }}</a></div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    <hr/>
{% endblock %}
{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#filtroformacao").change(function () {
                $.ajax({
                    url: '/jsonformacao/' + $(this).val() + '/',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (json) {
                        var options = "";
                        $.each(json, function (key, obj) {
                            options += '<div class="row padding-all">';
                            options += '<div class="small-4 large-4 columns">' + obj.formacao_nome + '</div>';
                            options += '<div class="small-4 large-4 columns">' + obj.campus_nome + '</div>';
                            options += '<div class="small-4 large-4 columns"><a href="' + obj.grupo_url + '">' +
                                    obj.grupo_nome + '</a></div>';
                            options += '</div>';
                        });
                        $("#resultado").html(options);
                        $("#filtrocampi").prop('selectedIndex',0);
                        $("#filtrocursos").prop('selectedIndex',0);
                    },
                    error: function (xhr, errmsg, err) {
                        alert(xhr.status + ": " + xhr.responseText);
                    }
                });
                return false;
            });

            $("#filtrocampi").change(function () {
                $.ajax({
                    url: '/jsoncampi/' + $(this).val() + '/',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (json) {
                        var options = "";
                        $.each(json, function (key, obj) {
                            options += '<div class="row padding-all">';
                            options += '<div class="small-4 large-4 columns">' + obj.formacao_nome + '</div>';
                            options += '<div class="small-4 large-4 columns">' + obj.campus_nome + '</div>';
                            options += '<div class="small-4 large-4 columns"><a href="' + obj.grupo_url + '">' +
                                    obj.grupo_nome + '</a></div>';
                            options += '</div>';
                        });
                        $("#resultado").html(options);
                        $("#filtroformacao").prop('selectedIndex',0);
                        $("#filtrocursos").prop('selectedIndex',0);
                    },
                    error: function (xhr, errmsg, err) {
                        alert(xhr.status + ": " + xhr.responseText);
                    }
                });
                return false;
            });

            $("#filtrocursos").change(function () {
                $.ajax({
                    url: '/jsoncursos/' + $(this).val() + '/',
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        'csrfmiddlewaretoken': '{{ csrf_token }}'
                    },
                    success: function (json) {
                        var options = "";
                        $.each(json, function (key, obj) {
                            options += '<div class="row padding-all">';
                            options += '<div class="small-4 large-4 columns">' + obj.formacao_nome + '</div>';
                            options += '<div class="small-4 large-4 columns">' + obj.campus_nome + '</div>';
                            options += '<div class="small-4 large-4 columns"><a href="' + obj.grupo_url + '">' +
                                    obj.grupo_nome + '</a></div>';
                            options += '</div>';
                        });
                        $("#resultado").html(options);
                        $("#filtroformacao").prop('selectedIndex',0);
                        $("#filtrocampi").prop('selectedIndex',0);
                    },
                    error: function (xhr, errmsg, err) {
                        alert(xhr.status + ": " + xhr.responseText);
                    }
                });
                return false;
            });

        });
    </script>
{% endblock %}