portal/conteudo/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('portal.conteudo.views',
                       # Noticias
                       url(r'^noticia/(?P<slug>[\w_-]+)/$', 'noticia_detalhe', name='noticia_detalhe'),
                       url(r'^noticia/preview/(?P<slug>[\w_-]+)/$', 'noticia_detalhe_preview',
                           name='noticia_detalhe_preview'),
                       url(r'^noticias/$', 'noticias_lista', name='noticias_lista'),

                       # Paginas
                       url(r'^pagina/(?P<slug>[\w_-]+)/$', 'pagina_detalhe', name='pagina_detalhe'),
                       url(r'^pagina/preview/(?P<slug>[\w_-]+)/$', 'pagina_detalhe_preview',
                           name='pagina_detalhe_preview'),

                       # Eventos
                       url(r'^evento/(?P<slug>[\w_-]+)/$', 'evento_detalhe', name='evento_detalhe'),
                       url(r'^evento/preview/(?P<slug>[\w_-]+)/$', 'evento_detalhe_preview',
                           name='evento_detalhe_preview'),
                       url(r'^eventos/$', 'eventos_lista', name='eventos_lista'),

                       # Videos
                       url(r'^video/(?P<slug>[\w_-]+)/$', 'video_detalhe', name='video_detalhe'),
                       url(r'^video/preview/(?P<slug>[\w_-]+)/$', 'video_detalhe_preview',
                           name='video_detalhe_preview'),
                       url(r'^videos/$', 'videos_lista', name='videos_lista'),

                       # Galerias
                       url(r'^galeria/(?P<slug>[\w_-]+)/$', 'galeria_detalhe', name='galeria_detalhe'),
                       url(r'^galeria/preview/(?P<slug>[\w_-]+)/$', 'galeria_detalhe_preview',
                           name='galeria_detalhe_preview'),
                       url(r'^galerias/$', 'galerias_lista', name='galerias_lista'),

                       # Tags
                       url(r'^tag/(?P<slug>[\w_-]+)/$', 'tags_lista', name='tags_lista'),

                       # Licitação
                       url(r'^licitacao/(?P<licitacao_id>\d+)/$', 'licitacao_detalhe', name='licitacao_detalhe'),
                       url(r'^licitacoes/$', 'licitacoes_lista', name='licitacoes_modalidades'),
                       url(r'^licitacoes/(?P<modalidade>\d+)/$', 'licitacoes_lista', name='licitacoes_lista'),
                       url(r'^licitacoes/(?P<modalidade>\d+)/(?P<ano>\d+)/$', 'licitacoes_lista',
                           name='licitacoes_ano'),
                       )

portal/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.contrib import admin


admin.autodiscover()

from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import search_view_factory
from portal.core.views import SearchViewSites
from rss_feed import UltimasNoticias

sqs = SearchQuerySet().order_by('-data_publicacao')

urlpatterns = patterns('',
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/static/facicon.ico', permanent=True)),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
                       url(r'^conteudo/', include('portal.conteudo.urls', namespace='conteudo')),
                       url(r'^selecao/', 'portal.core.views.selecao', name='selecao'),
                       url(r'^dirf/', 'portal.dirf.views.download', name='download'),
                       url(r'^admin_site_menu/(?P<site_id>\d+)/$', 'portal.core.views.admin_site_menu',
                           name='admin_site_menu'),


                       url(r'buscar/$', search_view_factory(
                           view_class=SearchViewSites,
                           template='search/search.html',
                           searchqueryset=sqs,
                           form_class=ModelSearchForm
                       ), name='buscar'),

                       # url(r'^guiadecursos/', 'portal.cursos.views.listagrupodecursos', name='listagrupodecursos'),
                       url(r'^cursos/(?P<slug>[\w_-]+)/(?P<campus>\d+)/(?P<formacao>\d+)/$', 'portal.cursos.views.listacursosdogrupo',
                           name='listacursosdogrupo'),
                       url(r'^curso/(?P<slug>[\w_-]+)/$', 'portal.cursos.views.exibecurso', name='exibecurso'),
                       url(r'^guiadecursoportal/', 'portal.cursos.views.guiadecursoportal', name='guiadecursoportal'),
                       url(r'^jsonformacao/(?P<formacao_id>\d+)/$', 'portal.cursos.views.jsonformacao',
                           name='jsonformacao'),
                       url(r'^jsoncampi/(?P<campus_id>\d+)/$', 'portal.cursos.views.jsoncampi', name='jsoncampi'),
                       url(r'^jsoncursos/(?P<curso_id>\d+)/$', 'portal.cursos.views.jsoncursos', name='jsoncursos'),
                       url(r'^json_campi/(?P<formacao_id>\d+)/$', 'portal.core.views.json_campi', name='json_campi'),
                       url(r'^json_cursos/(?P<formacao_id>\d+)/(?P<campus_id>\d+)/$', 'portal.core.views.json_cursos',
                           name='json_cursos'),

                       # urls para agenda de compromissos do reitor
                       url(r'^agenda/$', 'portal.agenda.views.compromissos', name='agenda'),
                       url(r'^agenda/(?P<dia>\d{2})/(?P<mes>\d{2})/(?P<ano>\d{4})/$', 'portal.agenda.views.compromissos', name='agenda'),

                       # urls de redirecionamento do antigoportal
                       url(r'^noticias/', 'portal.core.views.redirecionar_antigoportal', name='antigo_noticias'),
                       # url(r'^noticias/(?P<id_noticia>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^licitacoes/', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/(?P<id_licitacao>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^post/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file_from_name/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^pesquisar/', 'portal.core.views.redirecionar_antigoportal'),
                       # fim do redirecionamento de urls do antigoportal


                       url(r'^inicio/$', 'portal.core.views.home', name='home'),
                       url(r'^$', 'portal.core.views.hotsite', name='hotsite'),

                       # url para arquivo html de autenticidade para o google search console
                       url(r'^googlef0c85b6fba6510c7.html$', TemplateView.as_view(template_name="googlef0c85b6fba6510c7.html")),

                       # url para arquivo robots.txt
                       url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt")),

                       # url para arquivo wpad.dat
                       url(r'^wpad.dat$', TemplateView.as_view(template_name="wpad.dat")),

                       # url para favicon.ico
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/staticfiles/favicon.ico', permanent=True)),

                       # rss
                       # (r'^rss/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': {'ultimas': UltimasNoticias}}),
                       (r'^rss/$', UltimasNoticias()),
                       )

# Trecho utilizado para que o django sirva os arquivos do diretorio media
from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

portal/conteudo/views.py
# -*- coding: utf-8 -*-

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.contrib.sites.models import Site
from django.http.response import Http404
from django.utils import timezone
from django.views.decorators.cache import never_cache
from pure_pagination import Paginator, PageNotAnInteger
from taggit.models import TaggedItem

from portal.core.decorators import contar_acesso
from portal.conteudo.models import Noticia
from portal.conteudo.models import Pagina
from portal.conteudo.models import Evento
from portal.conteudo.models import Video
from portal.conteudo.models import Galeria
from portal.conteudo.models import Licitacao


@never_cache
@contar_acesso
def noticia_detalhe(request, slug):
    try:
        site = Site.objects.get(domain=request.get_host())
        noticia = Noticia.publicados.get(slug=slug, sites__id__exact=site.id)
    except Site.DoesNotExist, Noticia.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/noticia.html', {'noticia': noticia})


@never_cache
@login_required
def noticia_detalhe_preview(request, slug):
    try:
        site = Site.objects.get(domain=request.get_host())
        noticia = Noticia.objects.get(slug=slug, sites__id__exact=site.id)
    except Site.DoesNotExist, Noticia.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/noticia.html', {'noticia': noticia})


def noticias_lista(request):
    try:
        page = request.GET.get('page', 1)

    except PageNotAnInteger:
        page = 1

    try:
        site = Site.objects.get(domain=request.get_host())
        objects = Noticia.publicados.filter(sites__id__exact=site.id)
        paginator = Paginator(objects, request=request, per_page=25)
        noticias = paginator.page(page)

    except Site.DoesNotExist, Noticia.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/noticias_lista.html', {'noticias': noticias})


@never_cache
@contar_acesso
def pagina_detalhe(request, slug):
    try:
        pagina = Pagina.publicados.get(slug=slug)
    except Pagina.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/pagina.html', {'pagina': pagina})


@never_cache
@login_required
def pagina_detalhe_preview(request, slug):
    try:
        site = Site.objects.get(domain=request.get_host())
        pagina = Pagina.objects.get(slug=slug, sites__id__exact=site.id)
    except Site.DoesNotExist, Pagina.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/pagina.html', {'pagina': pagina})


@never_cache
@contar_acesso
def evento_detalhe(request, slug):
    try:
        site = Site.objects.get(domain=request.get_host())
        evento = Evento.publicados.get(slug=slug, sites__id__exact=site.id)
    except Site.DoesNotExist, Evento.DoesNotExist:
        raise Http404
    return render(request, 'conteudo/evento.html', {'evento': evento})


@never_cache
@login_required
def evento_detalhe_preview(request, slug):
    try:
        site = Site.objects.get(domain=request.get_host())
        evento = Evento.objects.get(slug=slug, sites__id__exact=site.id)

    except Site.DoesNotExist, Evento.DoesNotExist:
        raise Http404
    return render(request, 'conteudo/evento.html', {'evento': evento})


def eventos_lista(request):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1
    try:
        site = Site.objects.get(domain=request.get_host())
        objects = Evento.publicados.filter(sites__id__exact=site.id)
        paginator = Paginator(objects, request=request, per_page=25)
        eventos = paginator.page(page)

    except Site.DoesNotExist, Evento.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/eventos_lista.html', {'eventos': eventos})


@never_cache
@contar_acesso
def video_detalhe(request, slug):
    try:
        video = Video.publicados.get(slug=slug)

    except Video.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/video.html', {'video': video})


@never_cache
@login_required
def video_detalhe_preview(request, slug):
    video = get_object_or_404(Video, slug=slug)

    return render(request, 'conteudo/video.html', {'video': video})


def videos_lista(request):
    try:
        page = request.GET.get('page', 1)

    except PageNotAnInteger:
        page = 1

    try:
        site = Site.objects.get(domain=request.get_host())
        objects = Video.publicados.filter(sites__id__exact=site.id)
        paginator = Paginator(objects, request=request, per_page=25)
        videos = paginator.page(page)

    except Site.DoesNotExist, Evento.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/videos_lista.html', {'videos': videos})


@never_cache
@contar_acesso
def galeria_detalhe(request, slug):
    try:
        galeria = Galeria.publicados.get(slug=slug)

    except Site.DoesNotExist, Video.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/galeria.html', {'galeria': galeria})


@never_cache
@login_required
def galeria_detalhe_preview(request, slug):
    galeria = get_object_or_404(Galeria, slug=slug)

    return render(request, 'conteudo/galeria.html', {'galeria': galeria})


def galerias_lista(request):
    try:
        page = request.GET.get('page', 1)

    except PageNotAnInteger:
        page = 1

    try:
        site = Site.objects.get(domain=request.get_host())
        objects = Galeria.publicados.filter(sites__id__exact=site.id)
        paginator = Paginator(objects, request=request, per_page=25)
        galerias = paginator.page(page)

    except Site.DoesNotExist, Evento.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/galerias_lista.html', {'galerias': galerias})


def tags_lista(request, slug):
    try:
        page = request.GET.get('page', 1)

    except PageNotAnInteger:
        page = 1

    try:
        site = Site.objects.get(domain=request.get_host())

        # trecho utilizado para restringir a exibicao de objetos ao site atual
        objects = TaggedItem.objects.filter(tag__slug__iexact=slug)
        itens = []

        for i in objects:
            if site in i.content_object.sites.all():
                itens.append(i)

        paginator = Paginator(itens, request=request, per_page=25)
        tags = paginator.page(page)

    except Site.DoesNotExist, TaggedItem.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/tag_lista.html', {'tags': tags, 'slug': slug})


@never_cache
@contar_acesso
def licitacao_detalhe(request, licitacao_id):
    try:
        site = Site.objects.get(domain=request.get_host())
        licitacao = Licitacao.publicados.get(id=licitacao_id, sites__id__exact=site.id)
    except Site.DoesNotExist, Licitacao.DoesNotExist:
        raise Http404

    return render(request, 'conteudo/licitacao.html', {'licitacao': licitacao})


def licitacoes_lista(request, modalidade=None, ano=None):

    if modalidade:
        try:
            page = request.GET.get('page', 1)

        except PageNotAnInteger:
            page = 1
        try:
            site = Site.objects.get(domain=request.get_host())
            modalidade = modalidade

            if not ano:
                ano = str(timezone.now().year)

            objects = Licitacao.publicados.filter(sites__id__exact=site.id, modalidade=modalidade,
                                                  data_publicacao__year=ano)
            paginator = Paginator(objects, request=request, per_page=25)
            licitacoes = paginator.page(page)

        except Site.DoesNotExist, Licitacao.DoesNotExist:
            raise Http404

        anos = Licitacao.publicados.filter().datetimes('data_publicacao', 'year', order='DESC')

        return render(request, 'conteudo/licitacoes_lista.html', {'licitacoes': licitacoes, 'anos': anos, 'ano': ano,
                                                                  'modalidade': modalidade})
    else:
        site = Site.objects.get(domain=request.get_host())
        modalidades = Licitacao.get_modalidades_existentes(site)

        return render(request, 'conteudo/licitacoes_modalidades.html', {'modalidades': modalidades})

portal/conteudo/templates/conteudo/galeria.html
{% extends 'core/detalhe.html' %}
{% load thumbnail %}

{% block breadcrumbs %}
    <li><a href="{% url 'conteudo:galerias_lista' %}">Galeria</a></li>
    <li class="current"><a href="#">{{ galeria.titulo|truncatewords:"3" }}</a></li>
{% endblock %}

{% block edicao %}
    {% if user.is_authenticated %}
        {% if perms.conteudo.change_galeria %}
            {% load permissao_tags %}
            {% if user|tem_permissao:galeria %}
                <div class="row padding-top">
                    <div class="medium-12 columns text-right">
                        <a href="{% url 'admin:conteudo_galeria_change' galeria.id %}">
                            <i class="fi-page-edit"></i> Editar galeria
                        </a>
                        {% load contador_tags %}
                        / Visualizações: {% contador %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock edicao %}

{% block conteudo %}
    <div class="row padding-bottom" id="conteudo">
        {% if not galeria.esta_publicado %}
            <div class="row">
                <h2 class="vermelho padding-top-bottom text-center">
                    NÃO PUBLICADO - DATA DE PUBLICAÇÃO: {{ galeria.data_publicacao }}
                </h2>
            </div>
        {% endif %}
        <div class="row">
            <h1 id="titulo">{{ galeria.titulo }}</h1>

            <p class="padding-top-bottom texto-tamanho-pequeno">Publicado em: {{ galeria.campus_origem }} /
                {{ galeria.data_publicacao }}</p>
        </div>
        <div class="row">
            <ul class="clearing-thumbs small-block-grid-2 medium-block-grid-6" id="links">
                {% for imagem in galeria.imagens %}
                    <li>
                        <a class="th" href="{% thumbnail imagem.imagem 1000x800 upscale quality=80 %}"
                           title="{{ imagem.descricao }}">
                            <img src="{% thumbnail imagem.imagem 300x300 crop quality=80 %}"
                                 alt="{{ imagem.descricao }}"/>
                        </a>
                    </li>
                {% endfor %}
            </ul>
            {% autoescape off %}
                <article>
                    {{ galeria.texto|safe }}
                    {% if galeria.campus_origem.site %}
                        Site de origem: {{ galeria.campus_origem.site }}
                    {% endif %}
                </article>
            {% endautoescape %}

        </div>


        {% if galeria.tags.all and site in galeria.sites.all %}
            <div class="row collapse padding-bottom-duplo">
                <div class="small-12 columns">
                    <p class="sem-marcador no-margin">
                        Marcadores:
                        {% for tag in galeria.tags.all %}
                            <a href="{% url 'conteudo:tags_lista' slug=tag.slug %}">
                                <span class="radius secondary label texto-tamanho-pequeno">{{ tag.slug }}</span></a>
                        {% endfor %}
                    </p>
                </div>
            </div>
        {% endif %}

        <div class="row">
{#            <div class="medium-4 columns">#}
                {% if galeria.documentos %}
                    <h2 class="fundo-vermelho text-center">Arquivos relacionados</h2>
                    {% for documento in galeria.documentos %}
                        <div class="row padding-bottom">
                            <a href="{{ documento.arquivo.url }}" target="_blank"><i
                                    class="fi-download texto-tamanho-medio alinhamento-vertical">
                            </i>{{ documento.descricao }}
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
{#            </div>#}

{#            <div class="medium-4 columns">#}
                {% if galeria.galerias.all %}
                    <h2 class="fundo-vermelho text-center">Galerias relacionados</h2>
                    {% for galeria in galeria.galerias.all %}
                        <div class="row padding-bottom">
                            <a href="{{ galeria.get_absolute_url }}" target="_blank"><i
                                    class="fi-photo texto-tamanho-medio alinhamento-vertical">
                            </i>{{ galeria.titulo }}
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
{#            </div>#}

{#            <div class="medium-4 columns">#}
                {% if galeria.videos.all %}
                    <h2 class="fundo-vermelho text-center">Vídeos relacionados</h2>
                    {% for video in galeria.videos.all %}
                        <div class="row padding-bottom">
                            <a href="{{ video.get_absolute_url }}" target="_blank"><i
                                    class="fi-play-video texto-tamanho-medio alinhamento-vertical">
                            </i>{{ video.titulo }}
                            </a>
                        </div>
                    {% endfor %}
                {% endif %}
{#            </div>#}
        </div>

        <!-- The Gallery as lightbox dialog, should be a child element of the document body -->
        <div id="blueimp-gallery" class="blueimp-gallery blueimp-gallery-controls">
            <div class="slides"></div>
            <h3 class="title"></h3>
            <a class="prev">‹</a>
            <a class="next">›</a>
            <a class="close">×</a>
            <a class="play-pause"></a>
            <ol class="indicator"></ol>
        </div>
    </div>

{% endblock conteudo %}

portal/conteudo/templates/conteudo/licitacao.html
{% extends 'core/detalhe.html' %}
{% load thumbnail %}

{% block breadcrumbs %}
    <li><a href="{% url 'conteudo:licitacoes_modalidades' %}">Modalidades de Licitação</a></li>
    <li><a href="{% url 'conteudo:licitacoes_lista' licitacao.modalidade %}">Licitações</a></li>
    <li class="current"><a href="#">{{ licitacao.titulo|truncatewords:"5" }}</a></li>
{% endblock %}

{% block edicao %}
    {% if user.is_authenticated %}
        {% if perms.conteudo.change_licitacao %}
            {% load permissao_tags %}
            {% if user|tem_permissao:licitacao %}
                <div class="row padding-top">
                    <div class="medium-12 columns text-right">
                        <a href="{% url 'admin:conteudo_licitacao_change' licitacao.id %}">
                            <i class="fi-page-edit"></i> Editar licitação
                        </a>
                        {% load contador_tags %}
                        / Visualizações: {% contador %}
                    </div>
                </div>
            {% endif %}
        {% endif %}
    {% endif %}
{% endblock edicao %}

{% block conteudo %}
    <div class="row padding-bottom" id="conteudo">
        <h1 id="titulo">{{ licitacao.titulo }}</h1>

        <p><strong>Publicado em:</strong> {{ licitacao.campus_origem.nome }} / {{ licitacao.data_publicacao }}</p>

        <p><strong>Data de abertura:</strong> {{ licitacao.data_abertura }}</p>
        {% if licitacao.pregao_srp %}
            <p class="no-padding"><strong>Validade da Ata SRP:</strong> {{ licitacao.validade_ata_srp }}</p>
        {% endif %}
        {% if licitacao.possui_contrato %}
            <p class="no-padding"><strong>Vigência do contrato:</strong> {{ licitacao.vigencia_contrato_inicio }}
                ATÉ {{ licitacao.vigencia_contrato_fim }}</p>
        {% endif %}
        <div class="row">
            <div class="medium-12 columns no-padding">
                {% autoescape off %}
                    <article>
                        <p><strong>Situação:</strong> {{ licitacao.situacao|safe }}</p>
                    </article>
                {% endautoescape %}

                <div class="medium-12 columns no-padding">
                    {% autoescape off %}
                        <article>
                            <p><strong>Objeto:</strong> {{ licitacao.objeto|safe }}</p>
                        </article>
                    {% endautoescape %}

                    {% if licitacao.alteracoes.strip|length > 0 %}
                        {% autoescape off %}
                            <article>
                                <p><strong>Alterações:</strong> {{ licitacao.alteracoes|safe }}</p>
                            </article>
                        {% endautoescape %}
                    {% endif %}

                    <p><strong>Contato:</strong> {{ licitacao.email_contato }}</p>
                </div>

                {% if licitacao.tags.all %}
                    <div class="row collapse padding-bottom-duplo">
                        <div class="small-12 columns">
                            <p class="sem-marcador no-margin">
                                Marcadores:
                                {% for tag in licitacao.tags.all %}
                                    <a href="{% url 'conteudo:tags_lista' slug=tag.slug %}">
                                        <span class="radius secondary label texto-tamanho-pequeno">
                                            {{ tag.slug }}
                                        </span></a>
                                {% endfor %}
                            </p>
                        </div>
                    </div>
                {% endif %}


                <div class="row">
                    <div class="medium-12 columns">
                        {% if licitacao.anexolicitacao_set.all %}
                            <h2 class="fundo-vermelho text-center">Anexos</h2>
                            {% for arq in licitacao.anexolicitacao_set.all %}
                                <div class="row padding-bottom">
                                    <a href="{{ arq.arquivo.url }}" target="_blank"><i
                                            class="fi-download texto-tamanho-medio alinhamento-vertical">
                                    </i>{{ arq.descricao }}
                                    </a>
                                </div>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
{% endblock conteudo %}

portal/conteudo/templates/conteudo/licitacoes_lista.html
{% extends 'core/lista.html' %}
{% load thumbnail %}
{% load i18n %}

{% block breadcrumbs %}
    <li><a href="{% url 'conteudo:licitacoes_modalidades' %}">Modalidades de Licitação</a></li>
    <li class="current"><a href="#">Licitações</a></li>
{% endblock %}
{% block listagem %}
    <div class="row padding-top-bottom">
        <div class="small-12 columns">
            <h1>LICITAÇÕES{% if ano %} DE {{ ano }}{% endif %}</h1>

            <div class="row padding-top-bottom">
                {% if anos %}
                    Licitações do ano:
                    {% for a in anos %}
                        {% if a|date:"Y" != ano %}
                            <span class="round secondary label"><a
                                    href="{% url 'conteudo:licitacoes_ano' modalidade a|date:"Y" %}">{{ a|date:"Y" }}</a></span>
                        {% else %}
                            <span class="round radius label link-branco">{{ a|date:"Y" }}</span>
                        {% endif %}
                    {% endfor %}
                    </div>
                    <div class="row padding-top-bottom">
                {% endif %}
                {% if licitacoes %}
                    {% for licitacao in licitacoes.object_list %}
                        <div class="row padding-bottom-duplo">
                            <div class="row hover-cinza-claro">
                                <a href="{% url 'conteudo:licitacao_detalhe' licitacao.id %}">
                                    <div class="row">
                                        <div class="small-2 medium-1 columns no-padding">
                                            {% if not licitacao.encerrado %}
                                                <p class="padding-top-bottom fundo-verde no-margin espacamento-medio text-center"
                                                   title="Agendada/Em andamento">
                                                    {% else %}
                                                <p class="padding-top-bottom fundo-cinza no-margin espacamento-medio text-center"
                                                   title="Encerrada">
                                            {% endif %}
                                            {{ licitacao.data_publicacao|date:"d M" }}
                                            </p>
                                        </div>
                                        <div class="small-10 medium-11 columns">
                                            <div class="data-local texto-tamanho-xsmall">{{ licitacao.campus_origem.nome }}</div>
                                            <p class="no-margin espacamento-medio">{{ licitacao.titulo }}</p>
{#                                            <div class="data-local">#}
{#                                                {{ licitacao.get_campus_origem_display }}</div>#}
{#                                            <p class="no-margin espacamento-medio">{{ licitacao.titulo }}</p>#}
                                        </div>
                                    </div>
                                </a>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p class="padding-top-bottom fundo-vermelho no-margin espacamento-medio text-center">Registro não
                        encontrado.</p>
                {% endif %}
                </div>
        </div>
    </div>
{% endblock %}

{% block paginacao %}
    {#Início da paginação#}
    <div class="pagination-centered">
        <ul class="pagination" role="menubar" aria-label="Pagination">
            {% if licitacoes.has_previous %}
                <li class="arrow" aria-disabled="true">
                    <a href="?{{ licitacoes.previous_page_number.querystring }}">
                        <i class="fi-rewind"></i>
                    </a>
                </li>
            {% endif %}
            {% for page in licitacoes.pages %}
                {% if page %}
                    {% ifequal page licitacoes.number %}
                        <li class="current"><a href="">{{ page }}</a></li>
                    {% else %}
                        <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                    {% endifequal %}
                {% else %}
                    <li class="unavailable" aria-disabled="true"><a href="">&hellip;</a></li>
                {% endif %}
            {% endfor %}
            {% if licitacoes.has_next %}
                <li class="arrow">
                    <a href="?{{ licitacoes.next_page_number.querystring }}" class="arrow">
                        <i class="fi-fast-forward"></i>
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>
    {#Fim da paginação#}
{% endblock %}