portal/conteudo/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

urlpatterns = patterns('portal.conteudo.views',
                       # Noticias
                       url(r'^noticia/(?P<slug>[\w_-]+)/$', 'noticia_detalhe', name='noticia_detalhe'),
                       url(r'^noticia/preview/(?P<slug>[\w_-]+)/$', 'noticia_detalhe_preview',
                           name='noticia_detalhe_preview'),
                       url(r'^noticias/$', 'noticias_lista', name='noticias_lista'),

                       # Paginas
                       url(r'^pagina/(?P<slug>[\w_-]+)/$', 'pagina_detalhe', name='pagina_detalhe'),
                       url(r'^pagina/preview/(?P<slug>[\w_-]+)/$', 'pagina_detalhe_preview',
                           name='pagina_detalhe_preview'),

                       # Eventos
                       url(r'^evento/(?P<slug>[\w_-]+)/$', 'evento_detalhe', name='evento_detalhe'),
                       url(r'^evento/preview/(?P<slug>[\w_-]+)/$', 'evento_detalhe_preview',
                           name='evento_detalhe_preview'),
                       url(r'^eventos/$', 'eventos_lista', name='eventos_lista'),

                       # Videos
                       url(r'^video/(?P<slug>[\w_-]+)/$', 'video_detalhe', name='video_detalhe'),
                       url(r'^video/preview/(?P<slug>[\w_-]+)/$', 'video_detalhe_preview',
                           name='video_detalhe_preview'),
                       url(r'^videos/$', 'videos_lista', name='videos_lista'),

                       # Galerias
                       url(r'^galeria/(?P<slug>[\w_-]+)/$', 'galeria_detalhe', name='galeria_detalhe'),
                       url(r'^galeria/preview/(?P<slug>[\w_-]+)/$', 'galeria_detalhe_preview',
                           name='galeria_detalhe_preview'),
                       url(r'^galerias/$', 'galerias_lista', name='galerias_lista'),

                       # Tags
                       url(r'^tag/(?P<slug>[\w_-]+)/$', 'tags_lista', name='tags_lista'),

                       # Licitação
                       url(r'^licitacao/(?P<licitacao_id>\d+)/$', 'licitacao_detalhe', name='licitacao_detalhe'),
                       url(r'^licitacoes/$', 'licitacoes_lista', name='licitacoes_modalidades'),
                       url(r'^licitacoes/(?P<modalidade>\d+)/$', 'licitacoes_lista', name='licitacoes_lista'),
                       url(r'^licitacoes/(?P<modalidade>\d+)/(?P<ano>\d+)/$', 'licitacoes_lista',
                           name='licitacoes_ano'),
                       )

portal/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from django.views.generic import RedirectView
from django.contrib import admin


admin.autodiscover()

from haystack.forms import ModelSearchForm
from haystack.query import SearchQuerySet
from haystack.views import search_view_factory
from portal.core.views import SearchViewSites
from rss_feed import UltimasNoticias

sqs = SearchQuerySet().order_by('-data_publicacao')

urlpatterns = patterns('',
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/static/facicon.ico', permanent=True)),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^taggit_autosuggest/', include('taggit_autosuggest.urls')),
                       url(r'^conteudo/', include('portal.conteudo.urls', namespace='conteudo')),
                       url(r'^selecao/', 'portal.core.views.selecao', name='selecao'),
                       url(r'^dirf/', 'portal.dirf.views.download', name='download'),
                       url(r'^admin_site_menu/(?P<site_id>\d+)/$', 'portal.core.views.admin_site_menu',
                           name='admin_site_menu'),


                       url(r'buscar/$', search_view_factory(
                           view_class=SearchViewSites,
                           template='search/search.html',
                           searchqueryset=sqs,
                           form_class=ModelSearchForm
                       ), name='buscar'),

                       # url(r'^guiadecursos/', 'portal.cursos.views.listagrupodecursos', name='listagrupodecursos'),
                       url(r'^cursos/(?P<slug>[\w_-]+)/(?P<campus>\d+)/(?P<formacao>\d+)/$', 'portal.cursos.views.listacursosdogrupo',
                           name='listacursosdogrupo'),
                       url(r'^curso/(?P<slug>[\w_-]+)/$', 'portal.cursos.views.exibecurso', name='exibecurso'),
                       url(r'^guiadecursoportal/', 'portal.cursos.views.guiadecursoportal', name='guiadecursoportal'),
                       url(r'^jsonformacao/(?P<formacao_id>\d+)/$', 'portal.cursos.views.jsonformacao',
                           name='jsonformacao'),
                       url(r'^jsoncampi/(?P<campus_id>\d+)/$', 'portal.cursos.views.jsoncampi', name='jsoncampi'),
                       url(r'^jsoncursos/(?P<curso_id>\d+)/$', 'portal.cursos.views.jsoncursos', name='jsoncursos'),
                       url(r'^json_campi/(?P<formacao_id>\d+)/$', 'portal.core.views.json_campi', name='json_campi'),
                       url(r'^json_cursos/(?P<formacao_id>\d+)/(?P<campus_id>\d+)/$', 'portal.core.views.json_cursos',
                           name='json_cursos'),

                       # urls para agenda de compromissos do reitor
                       url(r'^agenda/$', 'portal.agenda.views.compromissos', name='agenda'),
                       url(r'^agenda/(?P<dia>\d{2})/(?P<mes>\d{2})/(?P<ano>\d{4})/$', 'portal.agenda.views.compromissos', name='agenda'),

                       # urls de redirecionamento do antigoportal
                       url(r'^noticias/', 'portal.core.views.redirecionar_antigoportal', name='antigo_noticias'),
                       # url(r'^noticias/(?P<id_noticia>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^licitacoes/', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       # url(r'^licitacoes/(?P<id_modalidade>\d+)/(?P<id_licitacao>\d+)/$', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^post/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^get_file_from_name/', 'portal.core.views.redirecionar_antigoportal'),
                       url(r'^pesquisar/', 'portal.core.views.redirecionar_antigoportal'),
                       # fim do redirecionamento de urls do antigoportal


                       url(r'^inicio/$', 'portal.core.views.home', name='home'),
                       url(r'^$', 'portal.core.views.hotsite', name='hotsite'),

                       # url para arquivo html de autenticidade para o google search console
                       url(r'^googlef0c85b6fba6510c7.html$', TemplateView.as_view(template_name="googlef0c85b6fba6510c7.html")),

                       # url para arquivo robots.txt
                       url(r'^robots.txt$', TemplateView.as_view(template_name="robots.txt")),

                       # url para arquivo wpad.dat
                       url(r'^wpad.dat$', TemplateView.as_view(template_name="wpad.dat")),

                       # url para favicon.ico
                       url(r'^favicon\.ico$', RedirectView.as_view(url='/staticfiles/favicon.ico', permanent=True)),

                       # rss
                       # (r'^rss/(?P<url>.*)/$', 'django.contrib.syndication.views.Feed', {'feed_dict': {'ultimas': UltimasNoticias}}),
                       (r'^rss/$', UltimasNoticias()),
                       )

# Trecho utilizado para que o django sirva os arquivos do diretorio media
from django.conf import settings

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
                            (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
                                'document_root': settings.MEDIA_ROOT}))

portal/core/models.py
# -*- coding: utf-8 -*-
import re
from unicodedata import normalize
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from filer.models import File, Image, Folder
from filer.fields.image import FilerImageField
from mptt.models import MPTTModel, TreeForeignKey


class Campus(models.Model):
    nome = models.CharField(max_length=50, verbose_name=u'Nome do Câmpus')

    class Meta:
        verbose_name = _(u'Campus')
        verbose_name_plural = _(u'Campi')

    def __unicode__(self):
        return self.nome


class TipoSelecao(MPTTModel):
    parent = TreeForeignKey('self', null=True, blank=True, related_name='pai', verbose_name='Tipo pai')
    titulo = models.CharField(max_length=100)
    slug = models.SlugField(max_length=100, unique=True, verbose_name=u'Identificador')

    class Meta:
        ordering = ('titulo',)
        verbose_name = _(u'Tipo de selecao')
        verbose_name_plural = _(u'Tipos de selecao')

    def __unicode__(self):
        return self.titulo


class Selecao(models.Model):
    STATUS = (
        ('ABT', 'Aberto'),
        ('AND', 'Em Andamento'),
        ('FNZ', 'Finalizado')
    )

    tipo = TreeForeignKey('TipoSelecao')
    titulo = models.CharField(max_length=100)
    url = models.CharField(max_length=250,)
    status = models.CharField(max_length=3, choices=STATUS)
    data_abertura_edital = models.DateTimeField(verbose_name=u'Data de Abertura do Edital')
    data_abertura_inscricoes = models.DateTimeField(verbose_name=u'Data de Abertura de Inscrições')
    data_encerramento_inscricoes = models.DateTimeField(verbose_name=u'Data de Fechamento das Incrições')
    data_publicacao = models.DateTimeField(verbose_name=u'Data de publicação')

    class Meta:
        ordering = ('titulo', 'status', 'data_abertura_edital')
        verbose_name = _(u'Selecao')
        verbose_name_plural = _(u'Selecoes')

    def __unicode__(self):
        return self.titulo


class SiteDetalhe(models.Model):
    ALINHAMENTO = (
        ('left', 'ESQUERDA'),
        ('right', 'DIREITA'),
        ('text-center', 'CENTRO')
    )
    site = models.OneToOneField('sites.Site')
    campus = models.ForeignKey('Campus', help_text=u'Câmpus ou local que este site está relacionado')
    destino = models.ForeignKey('Destino', help_text=u'Destino da página inicial')
    logo = FilerImageField()
    disqus_shortname = models.CharField(max_length=250, null=True, blank=True,
                                        help_text=u'ShortName do site no serviço de comentários DISQUS')
    hotsite = models.BooleanField(default=False)
    hotsite_background = FilerImageField(null=True, blank=True, related_name='hotsite_background_SiteDetalhe', verbose_name=u'Background do hotsite')
    hotsite_alinhamento_banners = models.CharField(max_length=15, choices=ALINHAMENTO, default='right', verbose_name=u'Alinhamento dos banners no Hotsite')
    modal = models.TextField(null=True, blank=True)
    social = models.TextField(null=True, blank=True)
    links_uteis = models.TextField(null=True, blank=True)
    endereco = models.TextField(null=True, blank=True)

    def __unicode__(self):
        return self.site.domain


class Destino(models.Model):
    TIPO = (
        ('PORTAL', u'PORTAL'),
        ('PORTAL_SECUNDARIO', u'PORTAL DE CAMPI'),
        ('PORTAL_PRO_REITORIAS', u'PORTAL DE PRÓ-REITORIAS'),
        ('BLOG', u'BLOG'),
        ('BLOG_SLIDER', u'BLOG SLIDER'),
        ('PAGINA', u'PÁGINA INDIVIDUAL'),
        ('INDEPENDENTE', u'PORTAL INDEPENDENTE'),
        ('REDIRECT', u'REDIRECIONAMENTO'),
    )

    tipo = models.CharField(max_length=100, choices=TIPO)
    caminho = models.CharField(max_length=200, help_text=u'Utilize o caminho app/template - Templates disponíveis:'
                                                         u'<br>core/portal.html'
                                                         u'<br>core/portal_secundario.html'
                                                         u'<br>core/blog.html'
                                                         u'<br>core/blog_slider.html'
                                                         u'<br>core/pagina.html'
                                                         u'<br>core/independente.html'
                                                         u'<br><br>Em caso de redirect use a url completa - '
                                                         u'Ex.: http://www.ifmt.edu.br')

    def __unicode__(self):
        return '%s: %s' % (self.tipo, self.caminho)

    @staticmethod
    def portal():
        return 'PORTAL'

    @staticmethod
    def portal_secundario():
        return 'PORTAL_SECUNDARIO'

    @staticmethod
    def portal_pro_reitorias():
        return 'PORTAL_PRO_REITORIAS'

    @staticmethod
    def blog():
        return 'BLOG'

    @staticmethod
    def blog_slider():
        return 'BLOG_SLIDER'

    @staticmethod
    def pagina():
        return 'PAGINA'

    @staticmethod
    def independente():
        return 'INDEPENDENTE'

    @staticmethod
    def redirect():
        return 'REDIRECT'


class ContadorVisitas(models.Model):
    criado_em = models.DateTimeField(auto_now_add=True, editable=False)
    modificado_em = models.DateTimeField(auto_now=True, editable=False)
    url = models.CharField(max_length=2000)
    contagem = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('-contagem', '-criado_em', '-modificado_em')
        get_latest_by = 'criado_em'
        verbose_name = _(u'Contador de visitas')
        verbose_name_plural = _(u'Contador de visitas')

    def __unicode__(self):
        return self.url


# cria um diretorio no filer para cada novo usuario
def create_user_profile(sender, instance, created, **kwargs):
    if created and not instance.is_superuser:
        diretorio = Folder(
            owner=instance,
            name=instance.username,
        )
        diretorio.save()

post_save.connect(create_user_profile, sender=User)


_punct_re = re.compile(r'[\t !"#$%&\'()*\-/<=>?@\[\\\]^_ºª`{|},:]+')


def slugify(text, delim=u'-'):
    """Generates an slightly worse ASCII-only slug."""
    result = []
    for word in _punct_re.split(text.lower()):
        word = normalize('NFKD', word).encode('ascii', 'ignore')
        if word:
            result.append(word)
    return unicode(delim.join(result))


def unicode_filename(sender, instance, created, **kwargs):
    if instance.original_filename:
        if not instance.original_filename == slugify(instance.original_filename):
            instance.original_filename = slugify(instance.original_filename)
            instance.save()

post_save.connect(unicode_filename, sender=File)
post_save.connect(unicode_filename, sender=Image)

portal/dirf/models.py
from django.db import models

# Create your models here.

portal/autorizacao/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.forms.models import BaseInlineFormSet


class PermissaoFormset(BaseInlineFormSet):
    def clean(self):
        super(PermissaoFormset, self).clean()

        # se houver erros no formset ja retorna para tratamento
        if any(self.errors):
            return

        for cleaned_data in self.cleaned_data:
            if not cleaned_data.get('sites', False):
                raise forms.ValidationError(u'Um usuário deve administrar pelo menos um site')

portal/agenda/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, get_object_or_404
from portal.agenda.models import Agenda
from django.core.urlresolvers import reverse
from datetime import date, datetime, timedelta # para trabalhar com datas e horarios
from django.db.models import Q # para trabalhar com condicao ou na queryset

from portal.core.decorators import contar_acesso
# Create your views here.

# http://programando-ads.blogspot.com.br/2014/12/manipular-semanas-com-python.html
# https://docs.djangoproject.com/en/1.11/ref/templates/builtins/#date
# https://docs.djangoproject.com/en/dev/ref/models/querysets/#range
# https://stackoverflow.com/questions/30782060/how-to-loop-over-datetime-range-in-django-templates
# https://stackoverflow.com/questions/1060279/iterating-through-a-range-of-dates-in-python
# https://docs.djangoproject.com/en/dev/topics/db/queries/#complex-lookups-with-q-objects #q object
# https://stackoverflow.com/questions/39441639/getting-the-date-of-the-first-day-of-the-week # corrigir erro ao identificar primeiro dia da semana

def daterange(start_date, end_date):
    for n in range(int((end_date - start_date).days)+1):
        yield start_date + timedelta(n)

@contar_acesso
def compromissos(request, dia=0, mes=0, ano=0):
    try:
        today = date(int(ano), int(mes), int(dia))
    except ValueError:
        #raise ValueError("data no formato incorreto")
        today = datetime.now()

    first_day = today - timedelta(days=today.isoweekday() %7)
    last_day = first_day + timedelta(days=6)
    agenda = Agenda.objects.filter(Q(inicio__range=(first_day, last_day)) | Q(fim__range=(first_day, last_day))).order_by('inicio', 'fim')

#    import calendar
#    print "calendário!!!"
#    print (calendar.monthcalendar(2017,8))

    return render(request, 'agenda/lista_compromissos.html', {'agenda': agenda, 'today': today, 'first_day': first_day, 'last_day': last_day, 'daterange': daterange(first_day, last_day)})

portal/menu/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render

# Create your views here.

portal/core/templates/core/blog.html
{% extends 'core/base.html' %}
{% load thumbnail %}
{% load embed_video_tags %}

{% block stylesheet %}
    <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/jquery.slick/1.3.8/slick.css"/>
{% endblock %}

{% block content %}
    {{ site.sitedetalhe.modal|safe }}
    {#Container central para as 2 colunas#}
    <div class="row">

        {#Container para mais notícias#}
        {% if banners or videos or galerias or eventos %}
            <div class="medium-8 columns padding-bottom">
        {% else %}
            <div class="small-12 columns padding-bottom">
        {% endif %}
        <h1><a href="{% url 'conteudo:noticias_lista' %}"><i class="fi-plus"></i> NOTÍCIAS</a></h1>
        {% for noticia in noticias.object_list %}
            <div class="row padding-bottom-duplo collapse">
                <div class="small-12 columns">
                    <p class="data-local texto-tamanho-xsmall no-margin">{{ noticia.data_publicacao|date:"d M" }}
                        - Publicado por {{ noticia.campus_origem.nome }}</p>

                    <h1><a href="{{ noticia.get_absolute_url }}">{{ noticia.titulo }}</a></h1>

                    <article>
                        {{ noticia.texto|safe|truncatewords:'100' }}
                    </article>

                    <div class="row collapse">
                        <div class="medium-4 medium-offset-8 columns">

                            <a href="{{ noticia.get_absolute_url }}" class="button small expand no-margin">Continue
                                lendo &raquo;</a>
                            {#                                <input type="submit" class="button small expand no-margin" value="Buscar Cursos">#}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}

        {% block paginacao %}
            {#Início da paginação#}
            <div class="pagination-centered">
                <ul class="pagination" role="menubar" aria-label="Pagination">
                    {% if noticias.has_previous %}
                        <li class="arrow" aria-disabled="true">
                            <a href="?{{ noticias.previous_page_number.querystring }}">
                                <i class="fi-rewind"></i>
                            </a>
                        </li>
                    {% endif %}
                    {% for page in noticias.pages %}
                        {% if page %}
                            {% ifequal page noticias.number %}
                                <li class="current"><a href="">{{ page }}</a></li>
                            {% else %}
                                <li><a href="?{{ page.querystring }}">{{ page }}</a></li>
                            {% endifequal %}
                        {% else %}
                            <li class="unavailable" aria-disabled="true"><a href="">&hellip;</a></li>
                        {% endif %}
                    {% endfor %}
                    {% if noticias.has_next %}
                        <li class="arrow">
                            <a href="?{{ noticias.next_page_number.querystring }}" class="arrow">
                                <i class="fi-fast-forward"></i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
            {#Fim da paginação#}
        {% endblock %}
        </div>
        {#Fim da div mais notícias#}

        {#Container para coluna à direita#}
        {% if banners or videos or galerias or eventos %}
            <div class="medium-4 columns padding-bottom">

                {#Eventos#}
                {% if eventos %}
                    <div class="row">
                        <h1><a href="{% url 'conteudo:eventos_lista' %}"><i class="fi-plus"></i> EVENTOS</a></h1>
                        {% for evento in eventos %}
                            <div class="row padding-bottom hover-cinza-claro">
                                <a href="{{ evento.get_absolute_url }}">
                                    <div class="row">
                                        <div class="small-3 columns text-center no-padding">
                                            <p class="padding-top-bottom fundo-verde no-margin espacamento-medio">
                                                {{ evento.data_inicio|date:"d M" }}
                                                {{ evento.data_publicacao|date:"Y" }}
                                            </p>
                                        </div>

                                        <div class="small-9 columns no-padding padding-left">
                                            <div class="data-local">
                                                {{ evento.get_campus_origem_display }}
                                            </div>
                                            <p class="espacamento-medio">{{ evento.titulo }}</p>
                                        </div>
                                    </div>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {#Fim da div eventos#}

                {#Galeria de fotos#}
                {% if galerias %}
                    <div class="row">
                        <h1><a href="{% url 'conteudo:galerias_lista' %}"><i class="fi-plus"></i> GALERIAS</a></h1>

                        <div class="row">
                            <ul class="example-orbit" data-orbit
                                data-options="animation:fade;animation_speed:500;bullets:false;slide_number:false;swipe:true;resume_on_mouseout:true;">
                                {% for galeria in galerias %}
                                    <li data-orbit-slide="{{ galeria.id }}">
                                        <a href="{{ galeria.get_absolute_url }}">
                                            {% if galeria.primeira_imagem %}
                                                <img
                                                        src="{% thumbnail galeria.primeira_imagem 640x350 crop quality=80 %}"
                                                        alt="{{ galeria.titulo }}"/>
                                            {% endif %}
                                            <div class="orbit-caption">
                                                <div class="small-2 columns text-center no-padding padding-top-bottom fundo-vermelho texto-tamanho-pequeno">
                                                    {{ galeria.data_publicacao|date:"d M" }}
                                                </div>
                                                <div class="small-10 columns">
                                                    <div class="data-local branco negrito texto-tamanho-pequeno">
                                                        {{ galeria.get_campus_origem_display }}
                                                    </div>
                                                    <p class="no-margin espacamento-medio branco texto-tamanho-pequeno">{{ galeria.titulo|truncatechars:'60' }}</p>
                                                </div>
                                            </div>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>

                            <ul class="small-block-grid-3 padding-top">
                                {% for galeria in galerias %}
                                    <li>
                                        <a data-orbit-link="{{ galeria.id }}">
                                            <img src="{% thumbnail galeria.primeira_imagem 190x100 crop quality=80 %}"
                                                 alt="{{ galeria.titulo }}"/>
                                        </a>
                                    </li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                {% endif %}
                {#Fim da div galeria de fotos#}

                {#Vídeos#}
                {% if videos %}
                    <div class="row">
                        <h1><a href="{% url 'conteudo:videos_lista' %}"><i class="fi-plus"></i> VÍDEOS</a></h1>
                        {% for video in videos %}
                            <div class="row">
                                <div class="flex-video">
                                    {% video video.url %}
                                </div>
                            </div>
                            <div class="row">
                                <a href="{{ video.get_absolute_url }}">
                                    <div class="data-local texto-tamanho-xsmall">{{ video.data_publicacao|date:"d M" }}
                                        - {{ video.campus_origem.nome }}</div>
                                    <p class="espacamento-medio">{{ video.titulo }}</p>
                                </a>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
                {#Fim da div vídeos#}

                {#Container para os banners especiais#}
                {% if banners %}
                    <div class="row">
                        <h1><i class="fi-link"></i> LINKS DE ACESSO</h1>
                        {% for banner in banners %}
                            <div class="row collapse padding-bottom">
                                <div class="row collapse hover-cinza-claro">
                                    <div class="small-2 medium-12 columns">
                                        <a href="{{ banner.url }}"
                                           {% if banner.nova_janela %}target="_blank"{% endif %}>
                                            <img src="{% thumbnail banner.arquivo 300x80 crop quality=80 %}"
                                                 data-tooltip class="has-tip"
                                                 title="{{ banner.titulo }}"/>
                                        </a>
                                    </div>
                                    <div class="small-10 columns show-for-small-only th">
                                        <div class="padding-left">
                                            <a href="{{ banner.url }}"
                                               {% if banner.nova_janela %}target="_blank"{% endif %}>
                                                <p class="espacamento-medio">{{ banner.titulo }}</p>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            </div>
        {% endif %}
        {#Fim da div da coluna à direita#}
        </div>
        {#Fim da div central para as 3 colunas#}
    </div>

{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $('#modal').foundation('reveal', 'open');
        });
    </script>
{% endblock %}

portal/core/templates/core/lista_selecao.html
{% extends 'core/pagina.html' %}
{% block conteudo %}
<titulo>Vestibulares e Seleções | Vestibulares</titulo>
<lista>
    <filtros>
        <a href="?status=ABT">Abertos</a>
        <a href="?status=AND">Em Andamento</a>
        <a href="?status=FNZ">Finalizado</a>
        <ul class="menu">
            <li><a href="?ano=2014">2014</a>
                <ul>
                   <li><a href="?ano=2013">2013</a></li>
                   <li><a href="?ano=2012">2012</a></li>
                </ul>
            </li>
        </ul>
    </filtros>
    <table cellspacing="0">
        <tr>
            <th class="data">Abertura</th>
            <th class="data">Status</th>
            <th>Editais</th>
        </tr>
        {% for item in lista %}
        <tr>
            <td class="data"><a href="{{ item.url }}" target="_blank">{{ item.data_abertura_edital|date:"d M Y" }}</a></td>
            <td class="data"><a href="{{ item.url }}" target="_blank">{{ item.get_status_display }}</a></td>
            <td><a href="{{ item.url }}" target="_blank">{{ item.titulo }}</a></td>
        </tr>
        {% endfor %}
    </table>
</lista>
{% endblock conteudo %}